# Generated by Django 4.1.9 on 2023-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permission_role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("restaurant manager", "Restaurantmanager"), ("employee", "Employee")],
                default="employee",
                max_length=18,
            ),
        ),
    ]
