# Generated by Django 4.1.9 on 2023-05-30 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_permission_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="permission_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="restaurant",
        ),
    ]
