# Generated by Django 4.1.9 on 2023-05-29 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("0", "Restaurant is normal (score:0)"),
                            ("1", "Restaurant is good (score:1)"),
                            ("2", "Restaurant is better (score:2)"),
                            ("3", "Restaurant is the best (score:3)"),
                        ],
                        default="0",
                        help_text="Vote for the restaurant",
                        max_length=4,
                        verbose_name="Vote value",
                    ),
                ),
                ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="menus.menu")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
