# Generated by Django 4.1.9 on 2023-05-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="menus.menu"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="value",
            field=models.IntegerField(
                choices=[
                    (0, "Restaurant is normal (score:0)"),
                    (1, "Restaurant is good (score:1)"),
                    (2, "Restaurant is better (score:2)"),
                    (3, "Restaurant is the best (score:3)"),
                ],
                default=0,
                help_text="Vote for the restaurant",
                verbose_name="Vote value",
            ),
        ),
    ]
