# Generated by Django 4.1.9 on 2023-05-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0001_initial"),
        ("votes", "0002_alter_vote_menu_alter_vote_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="menu",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="menus.menu"),
        ),
    ]
