# Generated by Django 4.1.9 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0004_alter_vote_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="value",
            field=models.IntegerField(
                choices=[
                    (1, "Restaurant is good (score:1)"),
                    (2, "Restaurant is better (score:2)"),
                    (3, "Restaurant is the best (score:3)"),
                ],
                default=1,
                help_text="Vote for the restaurant",
                verbose_name="Vote value",
            ),
        ),
    ]
