# Generated by Django 4.1.9 on 2023-05-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="manager",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="menus.restaurant"),
        ),
    ]
