# Generated by Django 4.1.9 on 2023-05-30 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0002_restaurant_manager_alter_menu_restaurant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="restaurant",
            unique_together={("name", "location")},
        ),
    ]
