# Generated by Django 4.1.9 on 2023-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0004_historicalrestaurant_historicalmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmenu",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="The Date of the Menu"),
        ),
        migrations.AddField(
            model_name="menu",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="The Date of the Menu"),
        ),
    ]
